# Generated by Django 2.1.2 on 2018-10-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre del restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='Dueño del chuzo'),
        ),
    ]
