# Generated by Django 2.1.2 on 2018-10-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platillo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platillo',
            old_name='precion',
            new_name='precio',
        ),
    ]
